name: LOLMViewDistance
options:
  bundleIdPrefix: com.lolm
  deploymentTarget:
    iOS: "14.0"
targets:
  LOLMViewDistance:
    type: application
    platform: iOS
    sources:
      - LOLMViewDistance
    dependencies:
      - sdk: CFNetwork.framework
      - sdk: WebKit.framework
      - sdk: UIKit.framework
      - sdk: Foundation.framework
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.lolm.viewdistance
      INFOPLIST_FILE: LOLMViewDistance/Info.plist
      CODE_SIGNING_ALLOWED: "NO"
      CODE_SIGN_IDENTITY: ""
      TARGETED_DEVICE_FAMILY: "1,2"
      IPHONEOS_DEPLOYMENT_TARGET: "14.0"
      CLANG_ENABLE_OBJC_ARC: "YES"
      OTHER_LDFLAGS: ["-lz"]
