name: LOLMViewDistance
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "15.0"
targets:
  LOLMViewDistance:
    type: application
    platform: iOS
    sources:
      - LOLMViewDistance
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.lolmviewdistance
      INFOPLIST_FILE: LOLMViewDistance/Info.plist
      CODE_SIGNING_ALLOWED: "NO"
      CODE_SIGN_IDENTITY: ""
